### PR TITLE
feat: lovely lesson layout

### PR DESCRIPTION
**Pull request by olizilla**
WIP on #15 

**Initial**
screenshot 2018-07-26 15 09 07

**oh noes**
screenshot 2018-07-26 15 09 56

**YASSSSSS QUEEEEN**
screenshot 2018-07-26 15 10 26

License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>

### CODE REVIEW

**Comment by mikeal** [comment]
Love it!

**Comment by mikeal** [comment]
One thing we lost was the "next lesson" button on success. Was that an oversight or is there a design reason you think it should be removed?

**Comment by olizilla** [comment]
Submit button should be replaced with the Next button. Perhaps that's too subtle.

**Comment by mikeal** [comment]
If we change the button color, maybe animate it, it'll be pretty obvious :)

**Comment by olizilla** [comment]
just to check, is the next button showing for you? It should already be changing colour and "submit" should be replaced with "next" when you complete an exercise.

**Comment by mikeal** [comment]
It is, I guess I just didn't notice it :(

Maybe we should add a bouncing CSS animation?

**Pull request merged**
